export function getDefectPhenomenon(defectId) {
  const defect = DefectLookup.find((d) => d.defect_id === defectId);
  return defect ? defect.defect_phenomenon : "Unknown defect";
}

export const DefectLookup = [
  {
    defect_id: 0,
    defect_phenomenon: "NONE",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 1,
    defect_phenomenon: "Oil pump tight Ø9 problem",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 2,
    defect_phenomenon: "Crack/Chip off",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 3,
    defect_phenomenon: "Extra Material in oil pump area",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 4,
    defect_phenomenon: "Puncture",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 5,
    defect_phenomenon: "Damage",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 6,
    defect_phenomenon: "Surface Dent",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 7,
    defect_phenomenon: "casting broken",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 8,
    defect_phenomenon: "Suface Unclean/NG",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 9,
    defect_phenomenon: "W/O Operation",
    defect_type: "Setting",
    cell: "3.1",
  },
  {
    defect_id: 10,
    defect_phenomenon: "Ø115 B/H",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 11,
    defect_phenomenon: "Surface NG/Dent",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 12,
    defect_phenomenon: "Blow Hole",
    defect_type: "Chronic",
    cell: "3.1",
  },
  {
    defect_id: 13,
    defect_phenomenon: "Unclean",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 14,
    defect_phenomenon: "deep cut",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 15,
    defect_phenomenon: "Ø32 O/S,U/S",
    defect_type: "Setting",
    cell: "3.1",
  },
  {
    defect_id: 16,
    defect_phenomenon: "Valve Leak",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 17,
    defect_phenomenon: "Fin Broken",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 18,
    defect_phenomenon: "Cottor Open",
    defect_type: "Sporadic",
    cell: "3.1",
  },
  {
    defect_id: 19,
    defect_phenomenon: "Ø42 O/s , U/s",
    defect_type: "Setting",
    cell: "3.1",
  },
  {
    defect_id: 20,
    defect_phenomenon: "Ø28 O/S,Ovality",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 21,
    defect_phenomenon: "M6 Tap Blunt  O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 22,
    defect_phenomenon: "CD OUT",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 23,
    defect_phenomenon: "CD OUT/Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 24,
    defect_phenomenon: "Ø55.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 25,
    defect_phenomenon: "Ø39.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 26,
    defect_phenomenon: "Ø27.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 27,
    defect_phenomenon: "Ø29.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 28,
    defect_phenomenon: "M8 Tap Blunt , O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 29,
    defect_phenomenon: "Ø55.4 Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 30,
    defect_phenomenon: "Depth O/S (Ø 39.4/ Ø55.4/Ø27.4)",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 31,
    defect_phenomenon: "Stud depth more",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 32,
    defect_phenomenon: "Spot Face Depth O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 33,
    defect_phenomenon: "Drum Hole Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 34,
    defect_phenomenon: "Ø57.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 35,
    defect_phenomenon: "dia 7.4 o/size ",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 36,
    defect_phenomenon: "Tool Breakage",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 37,
    defect_phenomenon: "Damage due to W/l by robot",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 38,
    defect_phenomenon: "Ø9.4 O/Size",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 39,
    defect_phenomenon: "Ø5.9 o/s",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 40,
    defect_phenomenon: "Stud hole Counter depth more",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 41,
    defect_phenomenon: "Spot face taper",
    defect_type: "Unknwon",
    cell: "3.1",
  },
  {
    defect_id: 42,
    defect_phenomenon: "Drill broken",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 43,
    defect_phenomenon: "Drill broken/ Tap",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 44,
    defect_phenomenon: "Spot facing depth Ø23.2 w/o",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 45,
    defect_phenomenon: "Cone plug pin unclean",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 46,
    defect_phenomenon: "Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 47,
    defect_phenomenon: "Inlet / Exhaust Guide Hole O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 48,
    defect_phenomenon: "Ø76 Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 49,
    defect_phenomenon: "Cam bore face taper",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 50,
    defect_phenomenon: "M8 tap broken",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 51,
    defect_phenomenon: "others",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 52,
    defect_phenomenon: "Ø42 O/S,Ovality",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 53,
    defect_phenomenon: "Ø29.4 Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 54,
    defect_phenomenon: "Tap Blunt / OverSize",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 55,
    defect_phenomenon: "Ø31.4 O/S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 56,
    defect_phenomenon: "Clone PLug Ø 4.9 O / S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 57,
    defect_phenomenon: "Height Under Size",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 58,
    defect_phenomenon: "Wrong Loading",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 59,
    defect_phenomenon: "Inlet Face Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 60,
    defect_phenomenon: "Ø6 Cone Plug hole O / S",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 61,
    defect_phenomenon: "Comb Room Chattering",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 62,
    defect_phenomenon: "In /Ex Seat Dia Over Size",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 63,
    defect_phenomenon: "Ø76 Chattering, O / S, CD OUT",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 64,
    defect_phenomenon: "Ø86 Cambore Taper",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 65,
    defect_phenomenon: "Tappet face chattering, Deep Cut",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 66,
    defect_phenomenon: "Roker Bore O / S, Ovality & Unclean",
    defect_type: "Unknown",
    cell: "3.1",
  },
  {
    defect_id: 67,
    defect_phenomenon: "NONE",
    defect_type: "Unknown",
    cell: "4",
  },
  {
    defect_id: 68,
    defect_phenomenon: "Bearing Dia. U/S",
    defect_type: "Chronic",
    cell: "4",
  },
  {
    defect_id: 69,
    defect_phenomenon: "Threading Dia. U/S",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 70,
    defect_phenomenon: "Face Width U/S",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 71,
    defect_phenomenon: "Face Burn",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 72,
    defect_phenomenon: "Width U/s",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 73,
    defect_phenomenon: "Wrong Loading",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 74,
    defect_phenomenon: "Flange Cut",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 75,
    defect_phenomenon: "Bore O/S",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 76,
    defect_phenomenon: "Bore U/S",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 77,
    defect_phenomenon: "CD OUT",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 78,
    defect_phenomenon: "UC/Tool Break/Blunt",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 79,
    defect_phenomenon: "Thread U/S",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 80,
    defect_phenomenon: "Thread Damage",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 81,
    defect_phenomenon: "R/O",
    defect_type: "Chronic",
    cell: "4",
  },
  {
    defect_id: 82,
    defect_phenomenon: "Pin Press",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 83,
    defect_phenomenon: "Re Hardening",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 84,
    defect_phenomenon: "Ovality",
    defect_type: "Chronic",
    cell: "4",
  },
  {
    defect_id: 85,
    defect_phenomenon: "Profile NG",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 86,
    defect_phenomenon: "Case Depth Checking",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 87,
    defect_phenomenon: "Sparking",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 88,
    defect_phenomenon: "Wrong Loading/ HardW/o Spline",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 89,
    defect_phenomenon: "Spline damage",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 90,
    defect_phenomenon: "Spline O/s",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 91,
    defect_phenomenon: "U/Setting",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 92,
    defect_phenomenon: "Taper more",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 93,
    defect_phenomenon: "Bore Unclean",
    defect_type: "Chronic",
    cell: "4",
  },
  {
    defect_id: 94,
    defect_phenomenon: "Tool Breakage/Blunt",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 95,
    defect_phenomenon: "Drill Broken",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 96,
    defect_phenomenon: "Drift",
    defect_type: "Setting",
    cell: "4",
  },
  {
    defect_id: 97,
    defect_phenomenon: "Bend",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 98,
    defect_phenomenon: "Taper Angle NG",
    defect_type: "Sporadic",
    cell: "4",
  },
  {
    defect_id: 99,
    defect_phenomenon: "NONE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 100,
    defect_phenomenon: "RCC COVER THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 101,
    defect_phenomenon: "CRANK SHAFT RIGHT THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 102,
    defect_phenomenon: "MAINSHAFT TREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 103,
    defect_phenomenon: "CLUTCH BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 104,
    defect_phenomenon: "PISTON BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 105,
    defect_phenomenon: "CAP NUT THREAD NG",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 106,
    defect_phenomenon: "STUD THREAD NG",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 107,
    defect_phenomenon: "CYLINDER BLOCK THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 108,
    defect_phenomenon: "PISTON RING BEND",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 109,
    defect_phenomenon: "CYLINDER BLOCK BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 110,
    defect_phenomenon: "CRANK SHAFT LEFT THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 111,
    defect_phenomenon: "PUSH ROD THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 112,
    defect_phenomenon: "SPEED SENSOR BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 113,
    defect_phenomenon: "FUEL INJECTOR BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 114,
    defect_phenomenon: "ACG WIRE CUT",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 115,
    defect_phenomenon: "ACG COVER SCRATCH",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 116,
    defect_phenomenon: "LCC PAINT PEAL OFF",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 117,
    defect_phenomenon: "LCC BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 118,
    defect_phenomenon: "SELF MOTOR DAMAGE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 119,
    defect_phenomenon: "OXYGEN SENSOR BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 120,
    defect_phenomenon: "SPARK PLUG BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 121,
    defect_phenomenon: "CYLINDER HEAD FINS BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 122,
    defect_phenomenon: "CYLINDER HEAD THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 123,
    defect_phenomenon: "ACG DAMAGE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 124,
    defect_phenomenon: "RCC THREAD FREE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 125,
    defect_phenomenon: "RCC BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 126,
    defect_phenomenon: "PISTON DENT",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 127,
    defect_phenomenon: "RCC BROKEN",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 128,
    defect_phenomenon: "CRANK SHAFT DAMAGE",
    defect_type: "Sporadic",
    cell: "3.2",
  },
  {
    defect_id: 200,
    defect_phenomenon: "NONE",
    defect_type: "Sporadic",
    cell: "FA01",
  },
];
